# Generated by Django 5.2.4 on 2025-07-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('type', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('date_of_operation', models.CharField(max_length=10)),
                ('op_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'operations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
